modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ThatJadenXgamer/Elysium/issues"
license = "GNU-LESSER-GENERAL-PUBLIC-LICENSE"

[[mods]]
modId = "elysium_api"
version = "${version}"
displayName = "Elysium-API"
authors = "ThatJadenXgamer"
description = '''
Elysium is a Library Mod full of various Java and Data-Driven utilities to help both Mod Developers and Modpack Creators.
'''
#logoFile = ""

[[dependencies.elysium_api]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elysium_api]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elysium_api]]
modId = "player_animation_library"
type = "required"
versionRange = "[1.0.14+mc1.21.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "elysium_api.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"
